# This controls automated builds at Travis & Shippable.

# http://blog.travis-ci.com/2014-12-17-faster-builds-with-container-based-infrastructure/
# Comment out for now because with it travis didn't build at all?
##sudo: false

# By default travis blacklists `gh-pages` branch.  We want it tested.
# http://docs.travis-ci.com/user/build-configuration/#Specify-branches-to-build
branches:
  only:
    - gh-pages
    - /.*/

language: node_js
node_js:
  - "0.11"  # Latest http://docs.travis-ci.com/user/languages/javascript-with-nodejs/#Provided-Node.js-Versions

# http://blog.travis-ci.com/2013-12-05-speed-up-your-builds-cache-your-dependencies/
cache:
  directories:
    - node_modules

after_script:
  - printenv

notifications:
  webhooks:
    urls:
      - https://webhooks.gitter.im/e/738a0684d6f3cc8e35ea
    on_success: change  # options: [always|never|change] default: always
    on_failure: always  # options: [always|never|change] default: always
    on_start: false     # default: false
