language: node_js
node_js:
  - "0.11"

notifications:
  webhooks:
    urls:
      - https://webhooks.gitter.im/e/738a0684d6f3cc8e35ea
    on_success: change  # options: [always|never|change] default: always
    on_failure: always  # options: [always|never|change] default: always
    on_start: false     # default: false
